version: 2
    
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: "daily"
  allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "daily" 
  allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"

- package-ecosystem: pip 
  directory: "/" 
  schedule:
    interval: "daily"
  allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
  labels:
      - "python"
      - "dependencies"
